### PR TITLE
adding new multi-file section for the PDP

### LINKED ISSUE #2753: Static egress IP addresses
The Scale team is launching a new feature that provides a set of static IP addresses for our users. 

Refer to the [launch document ](https://www.notion.so/prismaio/Static-egress-IPs-c917099fcc824cbd9c547568a19bf7fc) and the [Initiative document](https://www.notion.so/prismaio/Static-egress-IPs-for-Data-Proxy-0d5a3805a82d4848a83fd7cd0afbabb6).

@albertoperdomo is SME.
https://prisma-company.slack.com/archives/C5Z9TH6N9/p1642711034099300

### PR DESCRIPTION
**Pull request by tanberry**
This PR does several things (and was prompted by the need for a separate topic under PDP for the new feature of static IP addresses):

- Creates a second-level bucket for all PDP docs, to make it more visible in ToC
- Adds a new `about-platform.mdx` file, an Overview/Concept topic, that introduces the PDP at a high-level, and provides links off to the "child" topics
- Adds a new topic for static IP address
- Adds a new, separate topic for the Data Proxy
- Decreases the scrolling for pages and pages through one monolithic topic:-)
- Adds a link to our new Changelog for the PDP (see bottom of index.mdx file)

IMPORTANT: the following files will get redirects per this [PR on website-v8](https://github.com/prisma/website-v8/pull/432).  
FROM: /concepts/components/prisma-data-platform
TO: /concepts/data-platform

FROM: /concepts/components/prisma-data-platform#prisma-data-proxy
TO: /concepts/data-platform/data-proxy

When IA work is done, this will eventually move again, but we needed it fast for the IP addresses docs. #Agile

### CODE REVIEW

**Comment by tanberry** [comment]
@Nilu can you take a look at the preview docs, please? The title of the new section, Prisma Data Platform, is so long that it runs into/under the Early Access label.

**Review by martzoukos — APPROVED** [review]
It looks good (other than the small layout issue but you seem to be on top of it). I'm happy to see the PDP in its own section!

**Comment by albertoperdomo** [comment]
I see the page for PDP under Components is still there and there seems to be a disconnect between this and the child pages, at least on the left navigation?

image
The parent page is under components, the children under PDP.

**Comment by thebiglabasky** [comment]
The menu is off 
Screenshot_20220204-085155_Chrome

**Comment by tanberry** [comment]
Ooops, thanks @Hervé I'll fix that (hadn't had a chance to go back after last build)!

**Comment by albertoperdomo** [comment]
I think we should re-order the pages in the left navigation so that the platform page comes before the static ips page, ranking by relevance? But we can dissmiss this if we are sorting alphabetically or using other criteria.

image

Also, "About the Data" looks broken

**Comment by albertoperdomo** [comment]
It looks like when moving the page for Prisma Data Platform to a new directory, the embedded images broke and no longer load.

image

**Comment by albertoperdomo** [comment]
The item "About the Data Platform" in the left navigation should take users here - https://deploy-preview-2813--prisma2-docs.netlify.app/docs/concepts/data-platform/about-platform

But it's not clickable.

**Comment by tanberry** [comment]
Thanks @Alberto, I am about to work on these problems now, will have another deploy hopefully soon.

**Review by albertoperdomo — APPROVED** [review]

**Pull request merged**
