### PR TITLE
fix(data-proxy): Change name of npm script for migrate deploy

### PR DESCRIPTION
**Pull request by janpio**
... to make clearer what the script actually does.

Preview: https://docs-git-janpio-patch-12-prisma.vercel.app/data-platform/data-proxy#providing-the-connection-string-to-prisma-migrate

### CODE REVIEW

**Review by floelhoeffel — COMMENTED** [review]
Awesome!

How about snippets for dev, pull etc...too?

**Comment by janpio** [comment]
Out of scope for this PR. Zach will work on this.

**Review by zachtil — APPROVED** [review]
LGTM!

**Review by millsp — APPROVED** [review]

**Comment by ObamaTheLlama114** [comment]
Thanks @janpio for your contribution

**Pull request merged**
