### PR TITLE
Wrong DATABASE_URL format

### PR DESCRIPTION
**Pull request by garciajg**
This changes `postgresql://` DATABASE_URL to `postgres://`

### CODE REVIEW

**Comment by janpio** [comment]
Why do you think `postgresql` is wrong?

**Comment by garciajg** [comment]
@janpio I run linux and windows and it uses `postgres://` as the protocol, as well as some people having the same issue in the Slack channel with this as well. But it could be different in whatever system you guys use

**Comment by janpio** [comment]
In general Prisma works with both - we just convert to what works.

But the Postgres docs itself define `postgresql://`: 
https://www.postgresql.org/docs/10/libpq-connect.html#LIBPQ-CONNSTRING
> The URI scheme designator can be either postgresql:// or postgres://.

This is probably the reason why we usually use `postgresql://` in our docs.

**Comment by garciajg** [comment]
@janpio if that works for prisma then that's fine. I'm sure most Linux/macOS users will figure it out then. I sure did. Or maybe just add some sort of comments at the top of the page, something like:
**If `postgresql://` URI gives you issues, try doing `postgres://`**. But it's up you guys at this point.

**Comment by janpio** [comment]
I am sure it will not give you issues - or we have a bug that needs to be fixed :)

But adding a note somewhere in the docs might be worth it, instead of replacing all uses of it.

**Comment by mhwelander** [comment]
Hi folks - I've added a note at the top of this doc #408 that you should be able to use the 2 interchangeably, but that you might need to specify if you have issues. 

Thank you for prompting the discussion! 💚  I will close this PR and merge in the note.

**Comment by garciajg** [comment]
@mhwelander Thanks a lot!

**Pull request closed without merging**
