### PR TITLE
fix example relation between files

### PR DESCRIPTION
**Pull request by naor88**

### CODE REVIEW

**Comment by tanberry** [comment]
Thanks @naor88 ! We'll get a tech review on this and get it merged; your contributions are appreciated!

**Review by tomhoule — COMMENTED** [review]
I'm absolutely not familiar with this codebase — maybe @nikolasburk would know how to validate the changes?

**Comment by nikolasburk** [comment]
So, the first change to remove `.ts` from the file name in the import is certainly correct. I'm trying to validate the others as well 👍

**Comment by nikolasburk** [comment]
@TasinIshmam put on his detective hat and followed the types and the `createUser` signature from the article is:

```ts
export async function createUser(user: CreateUser, ctx: Context) {
  if (user.acceptTermsAndConditions) {
    return await ctx.prisma.user.create({
      data: user,
    })
  } else {
    return new Error('User must accept terms!')
  }
}
```

So it does expect only the `context` object and not an instance of `PrismaClient`, so all changes should be correct. Thanks so much for catching this @naor88 🙏

**Comment by tanberry** [comment]
Thanks so much @naor88 !!

**Comment by naor88** [comment]
Happy to help! :)

**Pull request merged**
