### PR TITLE
make index bullet a sub item of ref actions/integrity

### PR DESCRIPTION
**Pull request by janpio**
See https://deploy-preview-2766--prisma2-docs.netlify.app/docs/guides/database/using-prisma-with-planetscale

This was what I meant by "make it a sub bullet point" (or however I expressed it). The Index requirement follows from the ref actions/integrity change.

image

Suggestion re https://github.com/prisma/docs/pull/2708

### CODE REVIEW

**Comment by keerlu** [comment]
Sorry, I completely missed this PR. I considered a sub-bullet but just one looks very odd to me visually, more like a mistake than a deliberate subsection. I think this having the bullet immediately follow the 'referential actions' bullet is clear enough. Any thoughts @tanberry?

**Comment by tanberry** [comment]
Yeah, I agree that having the single, indented sub-bullet looks like a formatting mistake. I think a solution is to leave it as a regular bullet, right beneath Referntial Actions/Integrity bullet, but add a sentence at the very beginning saying something like:

 "Related to the use of referential actions is the use of foreign keys."
 
 Also, @keerlu instead of using the word "As..." use the word "Because..." (That's another translation thing... the word "as" is just too squirelly a word.)

**Comment by janpio** [comment]
To me the "visual mistake" actually represents the visual hierarchy of the content.. But you take it from here.

**Comment by janpio** [comment]
(I restored and changed the target branch to make it visible again what this PR really changes)

**Pull request closed without merging**
