### PR TITLE
Update 500-troubleshooting-relations.mdx

### PR DESCRIPTION
**Pull request by sably**

### CODE REVIEW

**Comment by janpio** [comment]
Aside: Why do we even use the `a_` and `b_` prefixes here for the relation field names?

**Comment by sably** [comment]
> Aside: Why do we even use the `a_` and `b_` prefixes here for the relation field names?

 they affect how you reference and query the data.

**Comment by janpio** [comment]
Yes, but `eats` and `eatenBy` would make much more sense here. I don'T know that the `a_` and `b_` mean here.

(This was more a question to whoever wrote this page and will review your edit)

**Comment by sably** [comment]
> 

whenever I write this page again I take a new conclusion? why?

**Comment by sably** [comment]
> Yes, but `eats` and `eatenBy` would make much more sense here. I don'T know that the `a_` and `b_` mean here.
> 
> (This was more a question to whoever wrote this page and will review your edit)

whenever I read this page again I take a new conclusion. why?

**Comment by nikolasburk** [comment]
Thanks for the PR @sably 💚 

Also: @janpio I agree with you, this example is confusing. I created an issue to review and improve it: https://github.com/prisma/docs/issues/5488

Nonetheless, the change from @sably is definitely correct since it catches a typo and makes the example (at least technically) correct.

**Pull request merged**
