### PR TITLE
Integration test issues

### LINKED ISSUE #2181: Incorrect code in integration test guide
In the [Integration Testing Guide](https://github.com/prisma/docs/blob/main/content/300-guides/150-testing/150-integration-testing.mdx) I noticed the following issues: 

### Incorrect model name ```Order```

[In a previous commit](https://github.com/prisma/docs/commit/6a566c22c7b69ad2e53e099825bf583195488613#diff-5024a68766a47e43130b850e135673f59591f46826d66413f0404f772fa24625L27) the ```Order``` model was renamed to ```CustomerOrder```. However there are still queries to the ```Order``` model In ```create-order.ts``` and ```__tests__/create-order.ts``` that have not been updated. 

### Temporary docker container persisting between tests

In the integration tests, a temporary postgres container is spun up and tests are run against that container. However, at the end of the test, this container is not stopped with a ```docker-compose down``` command. 

This is perhaps a bit nitpicky, but this can make the tests a bit flaky. Notably if the tests fail once for any reason, they will continue to fail, as the database has not been properly cleaned up after the previous run.

### PR DESCRIPTION
**Pull request by TasinIshmam**
Fix #2181

### CODE REVIEW

**Review by molebox — APPROVED** [review]
Good catch on the tear down. I was just persisting locally while creating this but this makes sense. Im not sure why you have changed the name of order to customer order, but im not against it either😄

seal-of-approval

**Comment by TasinIshmam** [comment]
Hi @molebox, 

I changed ```prisma.order``` to ```prisma.customerOrder``` in the queries because there was a corresponding name change in the example ```schema.prisma``` file in a [previous commit](https://github.com/prisma/docs/commit/6a566c22c7b69ad2e53e099825bf583195488613#diff-5024a68766a47e43130b850e135673f59591f46826d66413f0404f772fa24625L27). 

Currently the client queries are inconsistent with the provided schema. 

I'll merge this if everything looks good :+1:

**Comment by molebox** [comment]
Hey @TasinIshmam , oh right. yeah my bad! Good that you caught that. Thank you 😊

**Comment by TasinIshmam** [comment]
Happy to help :smile:

**Pull request merged**
