### PR TITLE
There is a typo.

### PR DESCRIPTION
**Pull request by love8587**

### CODE REVIEW

**Comment by love8587** [comment]
Please, commit it. I love Prisma!

**Comment by matthewmueller** [comment]
Thanks!

**Comment by pantharshit00** [comment]
Hey @love8587 

Would you mind signing our CLA for this project? Since our repos are new, we didn't have cla assistant setup at that time. 

Please sign it here: https://cla-assistant.io/prisma/prisma2-docs?pullRequest=9


If you don't sign this, we will, unfortunately, have to remove your commit.

**Comment by love8587** [comment]
@pantharshit00 Okay, I've agreed it. Thanks.

**Pull request merged**
