### PR TITLE
Getting Started Docs - Minor Fixes

### PR DESCRIPTION
**Pull request by robin-macpherson**
## Description

Small fixes to the Getting Started docs.

### CODE REVIEW

**Review by AlissonEnz — APPROVED** [review]

**Comment by mhwelander** [comment]
Hi @robin-macpherson ! Just checking in to see if this is ready to be merged. :)

**Comment by robin-macpherson** [comment]
Hi @mhwelander ! No for now this is still a draft but I will be finishing it either later this morning or definitely this week. I'll let you know as soon as it's ready! :)

**Comment by mhwelander** [comment]
@robin-macpherson Coolbeans - just making sure I wasn't ignoring you!

**Comment by robin-macpherson** [comment]
Ok @mhwelander this is now ready to be merged! Had to spend some time away unfortunately due to an insane month at my job 😓 but I'm back!

**Comment by mhwelander** [comment]
You are a 🌟 - hope things don't stay insane for too long!

**Pull request merged**
