### PR TITLE
feat: New Feedback Component 

### PR DESCRIPTION
**Pull request by nilubava**
#1145

### CODE REVIEW

**Comment by molebox** [comment]
Can this only be viewed on the live site due to serverless functions handling the thumbs up and down? @nilubava ?

**Comment by nilubava** [comment]
@molebox Yes, but you can check it locally using `netlify dev`

**Comment by molebox** [comment]
> @molebox Yes, but you can check it locally using `netlify dev`

Right, that's what I thought. Excited to see this!

**Comment by molebox** [comment]
I cant seem to view these changes. Im running `netlify dev` locally, nothing happens when i click a thumbs up or down 😕

**Review by molebox — APPROVED** [review]
This looks great @nilubava 😎

**Pull request merged**
