### PR TITLE
chore: move Prisma Client extensions level in sidebar to be above middleware

### LINKED ISSUE #4865: Move extensions a level above middleware on the sidebar

### PR DESCRIPTION
**Pull request by ruheni**
Closes #4865

- Renames "Prisma Client extensions" to "Extensions" in sidebar

### CODE REVIEW

**Comment by janpio** [comment]
Aside: Shouldnt they just be called `Client Extensions` in the navigation sidebar?

**Review by janpio — APPROVED** [review]

**Comment by ruheni** [comment]
Counter idea to yours: We could call it "Extensions". "Client extensions" is internal terminology

**Comment by janpio** [comment]
There could/will be other extensions to Prisma related things.
If we can handle that, and publicly for example call teh full feature "Prisma Client Extensions", why not.

**Comment by ruheni** [comment]
Sneaking in one more change to rename "Prisma Client extensions" to "Extensions"

**Review by janpio — CHANGES_REQUESTED** [review]
Pending conclusion of discussion at https://prisma-company.slack.com/archives/C043X6JBND6/p1686338728849179

**Review by janpio — APPROVED** [review]

**Comment by janpio** [comment]
Other suggestions from Slack discussion can be considered in separate PR.

**Pull request merged**
