### PR TITLE
Update Supported Databases to include Yugabyte

### PR DESCRIPTION
**Pull request by vvkgopalan**
Yugabyte YSQL is wire-compatible with Postgres. There is no additional setup required to integrate with Prisma (other than changing the .env file to reflect the appropriate database connection URL - which is necessary for Postgres in the first place). 
For an example app using Yugabyte & Prisma, view https://github.com/vvkgopalan/yugabyte-prisma2-examples/

### CODE REVIEW

**Comment by janpio** [comment]
We need to discuss internally if we are comfortable with promising full support if we are not running our full test suite on the database. "wire-compatible" is nice in theory, in practice there are a lot of possible gotchas. I will raise this internally.

**Comment by tomhoule** [comment]
We had this discussion, and we do not feel comfortable stating different implementations of the same protocol as supported without running our full test suite on them in CI. @janpio created issues about this for [Yugabyte](https://github.com/prisma/prisma-engines/issues/901) and [Cockroach](https://github.com/prisma/prisma-engines/issues/900).

**Review by janpio — CHANGES_REQUESTED** [review]
See discussion

**Comment by yoshuawuyts** [comment]
We have run the tests for both Yugabyte (https://github.com/prisma/prisma-engines/pull/1139) and Cockroach (https://github.com/prisma/prisma-engines/pull/1024) and unfortunately neither appear to work as-is with our Postgres connector. Even though they share a common network protocol with Postgres, the databases themselves differ in how they store and expose the data.

In order for Prisma to be compatible with Yugabyte and Cockroach we'll need to create dedicated connectors to support them. So unfortunately we can't claim we support either database quite yet. We may in the future though, but that's something that will need to be decided to be part of the roadmap.

**Pull request closed without merging**
