### PR TITLE
Remove dead link

### PR DESCRIPTION
**Pull request by katamotokosuke**
## Describe this PR
⚠ Sorry for the translated English.

I referred to prisma's excellent documentation. However, I found a dead link and removed it.

If you have an alternative link, please let me know. I will replace it with that link.

## Changes
Document Correction

## What issue does this fix?

Remove dead link.

### CODE REVIEW

**Comment by zachtil** [comment]
Thank you for reporting this @katamotokosuke!

@tomhoule @Jolg42 I've linked what seems to have been a moved file to be now the correct link. Can either of you verify that this is the correct one?

**Review by Jolg42 — APPROVED** [review]
nice, thanks!

**Comment by Jolg42** [comment]
New link looks good 👍🏼

**Review by janpio — APPROVED** [review]

**Comment by zachtil** [comment]
Thank you @Jolg42 and @janpio!

**Pull request merged**
