### PR TITLE
Prisma client commands updated in the documentation

### LINKED ISSUE #6284: Improve Documentation for Running Prisma Commands
### Description:
I would like to suggest an enhancement to the Prisma documentation regarding the execution of Prisma tasks, such as `prisma migrate`, `prisma generate`, and others. Currently, the instructions can be unclear or incomplete, which may lead to confusion for users, especially those who are new to Prisma.

**Proposed Improvements:**
1. **Clear Command Examples:** Provide specific examples of how to run each command, including common flags and options.
2. **Added Information:** Include little more information about the prisma commands such what they do , and the reason to do that for better understanding of using the commands at certain situations.
3. **Troubleshooting Tips:** Add a section for troubleshooting common issues encountered when running these commands.

These enhancements would greatly assist users in effectively utilizing Prisma and reduce potential friction in the onboarding process. Thank you for considering this suggestion!

### PR DESCRIPTION
**Pull request by AdityaSrivastava185**
**Overview:**
This pull request aims to enhance the Prisma documentation by providing clearer instructions and troubleshooting tips for commonly used commands, specifically `npx prisma migrate` and `npx prisma db push`.

**Changes Made:**
1. **Command Examples:** 
   - Added detailed examples for running `npx prisma migrate dev` and `npx prisma db push`, including common flags and options.

2. **Step-by-Step Guides:**
   - Included step-by-step instructions for setting up migrations and pushing schema changes.

3. **Explaination between using the both commands:**
   - Added explaination of the commands 
   - Included their use case , purpose and caution

**Rationale:**
These enhancements aim to provide a clearer understanding of how to effectively use Prisma commands, especially for new users. By including specific examples and troubleshooting tips, we can reduce confusion and improve the overall onboarding experience.

**Next Steps:**
- Review the changes and provide feedback 
- Consider additional sections or topics that could further enhance the documentation.

Resolves #6284

Thank you for considering this pull request! I look forward to your feedback.

### CODE REVIEW

**Comment by AdityaSrivastava185** [comment]
I would like to request @mhessdev and other reviewers to review the changes and approve or suggest 
Thank you

**Comment by jharrell** [comment]
Hi @AdityaSrivastava185 ! Thank you very much for your contribution. 

I think your rationale is sound. However, I think this could live in a better place. 

If you're interested in continuing this work, I believe you could do a few things:
1. update your branch off of main
2. either [edit this file](https://www.prisma.io/docs/orm/prisma-migrate/workflows/development-and-production) and/or link to it from places you believe it should be linked to.

 Does that make sense? Are you interested in continuing this?

**Comment by AdityaSrivastava185** [comment]
Hi @jharrell ,
Thank you so much for your feedback and encouragement regarding my contribution! I appreciate your insights and am eager to improve my work. I’m ready to update my branch off of main and make the necessary edits or links to enhance the project.
Looking forward to continuing this collaboration!

**Comment by AdityaSrivastava185** [comment]
Hello @jharrell I have updates the branch and done the changes , can you please review my pull request and merge this if everything is right 
Thank you

**Review by jharrell — APPROVED** [review]

**Comment by jharrell** [comment]
Thank you for your contribution!

**Comment by AdityaSrivastava185** [comment]
Thank you very much @jharrell to merge ,  looking forward to contribute more and connect with you and exploring new opportunities , advocating prisma more in communities ... 😄

**Comment by AdityaSrivastava185** [comment]
Hello @jharrell , i recently came across this issue on the prism.io page , can i work on this issue ?? 
Horizantal scroll is visible in the page , i would like to fix this issue 
Screenshot 2025-06-03 220131

**Pull request merged**
