### PR TITLE
change: width of content for docs pages

### LINKED ISSUE #4672: Change width of select pages in docs
https://prisma-company.slack.com/archives/C5Z9TH6N9/p1681718403394359

### PR DESCRIPTION
**Pull request by nilubava**
#4672

### CODE REVIEW

**Comment by nilubava** [comment]
@janpio @meletj So as discussed, we have increased the width of the content part here. Could you go through this ?

**Comment by janpio** [comment]
I find the docs navigation unbalanced, and the line length to much for general pages.

https://docs-git-feat-content-width-prisma.vercel.app/reference/api-reference/prisma-client-reference is somehow broken.

Specifically https://docs-git-feat-content-width-prisma.vercel.app/reference/database-reference/database-features is more readable now though.

**Comment by nilubava** [comment]
> I find the docs navigation unbalanced, and the line length to much for general pages.

@Techboidesign Do you have a good solution for this?

**Review by meletj — APPROVED** [review]

**Comment by janpio** [comment]
Yippieh!

**Pull request merged**
