### PR TITLE
Use HTMLAnchorElement for links instead of HTMLButtonElement

### LINKED ISSUE #5428: Text does not line break
https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/connection-pool#mongodb
image

That links does not fully need to be in a new line.

### LINKED ISSUE #5544: Check why anchor links are not working in Link component

### LINKED ISSUE #5574: Strange rendering of a hyperlinked sentence
The highlighted sentence [here](https://www.prisma.io/docs/orm/prisma-client/deployment/caveats-when-deploying-to-aws-platforms#aws-rds-proxy) is center-aligned but it's not clear why:

image

Here is the source for it:

https://github.com/prisma/docs/blob/main/content/200-orm/200-prisma-client/500-deployment/650-caveats-when-deploying-to-aws-platforms.mdx#L19

### LINKED ISSUE #5582: External links are <button> rather than <a>
External links being implemented with `<button>` elements rather than `<a>` elements results in unintuitive browser behaviour.

image

compared to

image

This makes it hard to "open in new tab" external links.

I am aware that this is technically unneccessary since that is the default behaviour, however it forces additional mental load on the user to distinguish between internal and external links before clicking.

This also means that command-click on mac or ctrl-click on windows does not work for these links which creates a very confusing experience

### LINKED ISSUE #5653: Link does not have URL preview
image

https://www.prisma.io/docs/orm/prisma-client/queries/full-text-search#:~:text=rows%20containing%20%27dog%27-,For%20the%20full%20range%20of%20supported%20operations%2C%20see%20the,.,-Sorting%20results%20by

Discussion: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1708350791176879

### LINKED ISSUE #5666: Middle click (or Right Click -> Open in new tab) on "Edit this page on GitHub" does not work
image

### PR DESCRIPTION
**Pull request by Tejs1**
## Describe this PR

Refactored `CustomLink` to use a styled `<a>` tag for better accessibility and security.

## Changes

- Replaced `CustomButton` with a Link styled component.
- Updated `CustomLink` to include `href`, `target`, and `rel `directly.
- Removed `goToPath` and `window.open.`
- Added `noreferrer ` attribute is a crucial security measure for external links opened in a new tab.
- Removed `inline-block` for link to be wrapped
- Updated `CSS` breaking changes due to `<a>` tag integration

image

 

## What issue does this fix?

Improves link handling for security and accessibility.
Fixes  https://github.com/prisma/docs/issues/5582 
Fixes  https://github.com/prisma/docs/issues/5574
Fixes  https://github.com/prisma/docs/issues/5666
Fixes  https://github.com/prisma/docs/issues/5653
Fixes  https://github.com/prisma/docs/issues/5544
Fixes  https://github.com/prisma/docs/issues/5428

### Has Open in new tab context menu, middle click works and link Preview in bottom #5582  #5666 #5653
Screenshot 2024-02-27 120006

### Link is aligned Properly #5574 

Screenshot 2024-02-27 1205s46

### Added Line break to Links  #5428 
Screenshot 2024-02-27 124940

### CODE REVIEW

**Comment by Tejs1** [comment]
Hey @janpio , there could be additional breaking changes similar to [below one](https://github.com/prisma/docs/pull/5678/commits/058dd4542b6e75d3b0abf0cf8e5b3217c47d5d48). Could you please approve the Vercel fork deployment so we can identify any issues using Lost Pixel Bot?

image

**Comment by janpio** [comment]
I can't, but I can let the relevant team know to look at this.

(Thanks for taking a look at all these issues, quite some are from my observations - so I am looking forward to get these fixed)

**Comment by Tejs1** [comment]
Glad to help 🙌

**Comment by mhessdev** [comment]
Thanks for doing this, @Tejs1. I have approved the deployment. The changes look good to me, but we will need to wait for a web engineer to take a look before we can push this through. I really appreciate the help! We will get this in once we know it's all working correctly.

**Comment by Tejs1** [comment]
Sorry accidently deleted the branch while testing. @mhessdev Thanks for looking into it.
Can you reauthorize.
My bad.

**Comment by Tejs1** [comment]
@carlagn @mhessdev Any updates? lemme know if you want any changes.
I tested with lost pixel in my repo only link line breaks were changed in 95 shots[pages/routes]
like following
image

**Comment by jharrell** [comment]
Hi @Tejs1 

Thanks for your PR here. We recently updated our docs repo from Gatsby to Docusaurus. We resolved a number of accessibility issues. I'm unsure if this is one of them. You can find our modified links here: https://github.com/prisma/docs/blob/a114584a9b2800b686eaaa7f388c683e61a350d4/src/theme/MDXComponents.tsx#L95-L107

**Comment by jharrell** [comment]
Closing as resolved by our migration to Docusaurus. Thank you very much for your contribution, however!

**Pull request closed without merging**
