### PR TITLE
feat: Linkable search

### LINKED ISSUE #380: Linkable search results
Sometimes I want to link to the search results page in Slack. It would nice if the URL would be updated to reflect the current search term.

### PR DESCRIPTION
**Pull request by nilubava**

### CODE REVIEW

**Comment by Jolg42** [comment]
@nilubava https://docs-git-linkable-search-prisma.vercel.app/?query=mongo&page=1 looks like this for me in Firefox / Chrome
Screen Shot 2022-08-03 at 17 27 23

It does open the search box and adds the keyword, but it doesn't load the results.

**Comment by nilubava** [comment]
@Jolg42 Can you check now?

**Comment by janpio** [comment]
Does update URL, which is linkable: https://docs-git-linkable-search-prisma.vercel.app/?query=referential&page=1

Clicking into search box shows endless spinner though and seems to load things 🔴 

Are pages like https://docs-git-linkable-search-prisma.vercel.app/?query=test&page=1 indexable by Google? They optimally should not be (even when discovering these should be hard for Google - but they are not for example linked here.)

**Comment by Jolg42** [comment]
@nilubava It does work and loads results on my browser (Firefox) after I cleared the cache, nice!

@janpio we could add these query parameters to the robots.txt file to ignore them like this 
```
# duplicated so we can ignore them independently of their position in the url
Disallow: /*?query=*
Disallow: /*?page=*
Disallow: /*&query=*
Disallow: /*&page=*
```

**Comment by nilubava** [comment]
@janpio "Clicking into search box shows endless spinner though and seems to load things 🔴" can you give me the steps to reproduce this?

**Comment by janpio** [comment]
1. Open https://docs-git-linkable-search-prisma.vercel.app/
2. Click into search box
3. Observe endless spinner and visual impression it loading stuff over and over

**Comment by Jolg42** [comment]
Indeed, the search works when you enter a keyword.
But the endless spinner is unexpected when clicking on search, the input is empty and looks like this
Screenshot 2022-08-15 at 18 03 44

**Comment by nilubava** [comment]
@Jolg42 @janpio Can you confirm if this is good to go?

**Comment by Jolg42** [comment]
Looks good to me 👍🏼

**Pull request merged**
