### PR TITLE
Remove jest-mock-extended unused reference

### LINKED ISSUE #3135: Integration test page references unused jest-mock-extended
[This topic](https://www.prisma.io/docs/guides/testing/integration-testing#prerequisites) advertises the usage of `jest-mock-extended`. But, it's not used on this guide, since it's a integration test including a real database access.

### PR DESCRIPTION
**Pull request by isaacbatst**
## Describe this PR
It removes the a usage reference for `jest-mock-extended` on [this page](https://www.prisma.io/docs/guides/testing/integration-testing#prerequisites)

## Changes

Only removes the reference.

## What issue does this fix?

Fixes #3135 

## Any other relevant information

--

### CODE REVIEW

**Comment by tanberry** [comment]
Thanks @isaacbatst . When you say that the [unit testing guide](https://www.prisma.io/docs/guides/testing/unit-testing)) doesn't use jest-mock-extended I am not sure what you mean. Do you mean that one can skip the "Mocking the Prisma client"section, and connect to a real DB, and thus not use jest?

**Comment by isaacbatst** [comment]
Hey @tanberry! Actually, the unit testing guide mentions **and** uses the `jest-mock-extended` as it is meant to be.

For the other side, the[ integration testing guide ](https://www.prisma.io/docs/guides/testing/integration-testing#prerequisites)**does not uses the mock**, since it is a test that is meant to reach a testing database. 

This integration guide has a warning suggesting the lib is been used, but it is not. So, I think this warning should be removed.

**Comment by isaacbatst** [comment]
Hey @tanberry  just a ping here 🏓

**Comment by ruheni** [comment]
👋

Thanks for the contribution. The change makes sense. I'll go ahead an merge it. 🙂

**Pull request merged**
