### PR TITLE
Change @db.Array(ObjectID) to @db.ObjectID

### LINKED ISSUE #2475: Add JSON collection example for MongoDB many to many relation (Epic 2)
https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#mongodb

Example from @dpetrick in internal Slack: https://prisma-company.slack.com/archives/C013RMLGE72/p1636033930023300?thread_ts=1636032952.021700&cid=C013RMLGE72

### PR DESCRIPTION
**Pull request by matthewmueller**
Closes: https://github.com/prisma/docs/issues/2475

## Describe this PR

I fixed a typo

### CODE REVIEW

**Review by janpio — APPROVED** [review]

**Comment by keerlu** [comment]
I've changed all the 'search and replace' type uses of `@db.Array`, but there are two remaining notes that I'm not sure about how to rephrase, or whether the example needs to change:

1. in https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#model-field-type-modifiers

image

2. in https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#mongodb

image

**Comment by janpio** [comment]
- 1), the sentence is obsolete and can be removed now I think. The example needs to be adapted.
- 2), the syntax and description needs to be adapted - it's simple lists now with `@db.ObjectId`

**Comment by matthewmueller** [comment]
+1 to what Jan said

**Review by janpio — APPROVED** [review]

**Comment by keerlu** [comment]
Thanks - I've now done this

**Pull request merged**
