### PR TITLE
feat(logging): Add parameter logging to example

### PR DESCRIPTION
**Pull request by janpio**

### CODE REVIEW

**Review by tanberry — APPROVED** [review]

**Comment by tanberry** [comment]
Looks good to me, @janpio, from a words view; do we want to wait for a further tech review or merge?

**Comment by janpio** [comment]
I think it is correct, obviously, but I would not be mad if you found someone from Client team to confirm - especially the example data it logs for these queries - your call.

**Comment by matthewmueller** [comment]
Looks good!

**Comment by tanberry** [comment]
Thanks @janpio !

**Pull request merged**
