### PR TITLE
Update 150-introspection.mdx

### PR DESCRIPTION
**Pull request by NicolaGenesinJetty**
Virtual fields are removed for planetscale

### CODE REVIEW

**Comment by janpio** [comment]
Did you open a bug report in prisma/prisma about this? That should probably not be happening - so a description of what you are seeing would be interesting.

**Comment by Jolg42** [comment]
Page where the sentence can be found: https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/relational-databases/introspection-node-planetscale

**Comment by Jolg42** [comment]
@NicolaGenesinJetty Could you check your schema? It should look like this:
```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

datasource db {
  provider     = "mysql"
  url          = env("DATABASE_URL")
  relationMode = "prisma" // <--- Make sure that this line is present
}
```

This is mentioned in the first step here https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/relational-databases/connect-your-database-typescript-planetscale

Maybe it could use a reminder on https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/relational-databases/introspection-node-planetscale

**Comment by NicolaGenesinJetty** [comment]
@Jolg42 I was missing that relationMode line. I've added it but `npx prisma db pull` removes virtual relations anyway.

**Comment by Jolg42** [comment]
@NicolaGenesinJetty Could you give us info we can use to get to a reproduction? We are very interested into checking this.

The best would be to [open a bug report here](https://github.com/prisma/prisma/issues/new?assignees=&labels=kind%2Fbug&template=bug_report.yml)

**Comment by NicolaGenesinJetty** [comment]
whoops I just checked the "Describe this PR" and it's empty. Weird, sorry about this.

Submitted bug report with more infos here https://github.com/prisma/prisma/issues/16100

**Pull request closed without merging**
