### PR TITLE
fix: Techswitcher CPU usage breaking docs

### LINKED ISSUE #511: High memory and CPU usage on pages with techswitchers, going blank
High memory and CPU usage on pages with techswitchers

https://prisma-company.slack.com/archives/C5Z9TH6N9/p1592853060004300

### PR DESCRIPTION
**Pull request by nilubava**
#666

### CODE REVIEW

**Comment by janpio** [comment]
What was the reliable reproduction we had found for this? Seems the issue has not been updated to contain it.

**Comment by mhwelander** [comment]
<s>@janpio It's in this issue: https://github.com/prisma/docs/issues/511</s> Never mind, no it isn't! Here: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1598295261120300

**Comment by janpio** [comment]
Ok, so:

> I could just reproduce the "https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch-sql-- will make your browser hang" thing.
> I went to docs.prisma.io and clicked on "Start from scratch (Prisma Migrate) (15 min)" and then tried to use the "Back" button on my mouse (not sure if that step really influenced it at all).
> Afterwards the tab goes bonkers

**Review by janpio — APPROVED** [review]
I can still reproduce this on docs.prisma.io, so it was not a fluke.
I can not reproduce this any more in the deploy preview from Netlify in this PR here: https://deploy-preview-827--prisma2-docs.netlify.app

Sometimes the dropdown take a bit to show up, but I think that is something we can fix later if we want to - as long as it does not kill our user's browsers any more this is worth merging.

**Comment by mhwelander** [comment]
My browser still has issues if you go to: https://deploy-preview-827--prisma2-docs.netlify.app/getting-started/setup-prisma/add-to-existing-project

Specifically the 'loading' icon keeps spinning and the full contents of the page don't load (when you scroll, part of the content is cut off)

**Comment by janpio** [comment]
Can confirm @mhwelander  - something is funky there. (loading icon is in the tab of Chrome for me)

**Comment by mhwelander** [comment]
Same - loading icon is in the tab.

**Comment by nilubava** [comment]
@mhwelander this seems to happen only when we are opening the link as https://deploy-preview-827--prisma2-docs.netlify.app/getting-started/setup-prisma/add-to-existing-project and not as https://deploy-preview-827--prisma2-docs.netlify.app/getting-started/setup-prisma/add-to-existing-project-typescript-postgres

Will there be any situations where we have to provide links like this? I thought we always had to link to the language and db in url.

**Comment by mhwelander** [comment]
@nilubava We use the non-technology-specific link (on the site, on Twitter) - I'm also not sure if the link checker would work with the -postgres-typescript part?

**Comment by janpio** [comment]
Even if we would replace all links, it should not really break 🤷

**Comment by nilubava** [comment]
@janpio This was not the assumption. If we need to include the paths without lang and db in the url, we can move this to a separate issue ticket.

**Comment by nilubava** [comment]
Nvm, I will push a fix for this in the same PR

**Comment by nilubava** [comment]
@mhwelander Can you confirm whether the issue has been resolved?

**Comment by mhwelander** [comment]
@nilubava The performance issue is no more!

One small thing - I notice that the default redirect no longer occurs (add-to-existing-project does not become add-to-existing-project-typescript-postgres)

Is that because the URL rewrite was causing the performance issue?

I think we can live with that - however, a small 'bug':

1. Go to add-to-existing-project
2. Change to Javascript and MySQL
3. Try to change back to TypeScript and PostgreSQL

Expected result: URL changes to add-to-existing-project-typescript-postgres

Actual: URL is add-to-existing-project-typescript-mysql (mysql part should update, but doesn't).

**Comment by janpio** [comment]
> I think we can live with that - however, a small 'bug':

That would be problematic as for Google (and other search engines) the same content exists twice on different URLs. If this is really the state to be, it needs to be handled properly with `canonical` etc.

**Comment by mhwelander** [comment]
Alternatively - we do an actual redirect

**Comment by nilubava** [comment]
@mhwelander @janpio That certainly was not an unavoidable bug. I have fixed it now. Except for the slow select dropdown update issue, everything works good now. I have created a new issue for this in https://github.com/prisma/docs/issues/852

**Pull request merged**
