### PR TITLE
fix: some ineffective finally clauses

### PR DESCRIPTION
**Pull request by LumaKernel**
## Changes

Code snippets for short living scripts have ineffective finally chain.

```ts
(async()=>{ console.log(1); throw 1 })()
  .catch(() => { console.log(2); process.exit(1) })  // or re-throw.
  .finally(() => { console.log(3) }) // unreachable
```

Finally clause with unsafe catch clause has no effect as _finally_. (It's run when no error, but if it's desired, `.then` is enough.)

I chosen the style below.

```ts
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
```

### CODE REVIEW

**Comment by tanberry** [comment]
Thanks @LumaKernel ! We will get a tech review done on this and then hopefully merge soon. We appreciate your contribution!

**Comment by matthewmueller** [comment]
Thanks @LumaKernel, I agree with your style.

I'm tempted to suggest:

```ts
main()
  .catch(err => console.error(err))
  .finally(() => prisma.$disconnect())
```

Since it's simpler. But, there's no easy way to apply a non-zero exit code.

So, your changes LGTM!

**Comment by janpio** [comment]
We could use this opportunity to normalize with https://github.com/prisma/prisma-examples/blob/latest/javascript/script/script.js#L93-L100

**Comment by LumaKernel** [comment]
> We could use this opportunity to normalize with https://github.com/prisma/prisma-examples/blob/latest/javascript/script/script.js#L93-L100

@janpio As I mentioned in the description, its `finally` usage has no effect as `finally` because `catch` will end the process. It's the same as following, and if `main()` throws, `prisma.$disconnect()` wouldn't be run.

```ts
main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
```

**Comment by LumaKernel** [comment]
@matthewmueller 
I agree with you. No simple default with taking care of exit code. I think such scripts can be reader's important parts like deployments that should be failed with exit code. We can add a note with your suggestion like 'pay attention to unhandled promises. If you are using Node.js v14 or later, you can explicitly use `--unhandled-rejections=throw` for `node`(`ts-node`) or use `process.exit(1)`'

**Comment by janpio** [comment]
> @janpio As I mentioned in the description

Yes, exactly why making sure these two use the same pattern makes sense if the current state doesn't work.

**Comment by millsp** [comment]
Could we move `await prisma.$disconnect()` inside of the `main` function and have a single catch clause. This makes it somewhat easier to read and understand:
```ts
// all of that happens on success
async function main() {
	  // ... prisma stuff
	  
	  await prisma.$disconnect()
}

// all of this happens on error
main().catch(async (e) => {
	  console.error(e)
	  await prisma.$disconnect()
	  process.exit(1)
})
```

**Comment by janpio** [comment]
We would probably want a pattern where we do _not_ expect users to manually $disconnect on success - that should not be necessary at all.

**Comment by LumaKernel** [comment]
I suspect whether it is needed on failure too. I think any short living scripts are obviously not _long running_ and it is against the case described in https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/connection-management#calling-disconnect-explicitly

**Comment by LumaKernel** [comment]
Hi. My last comment is acceptable? If so, I'll add a commit.

**Comment by tanberry** [comment]
Hi @LumaKernel yes, please do make one more commit to wrap up the decisions/convo, and let's get this merged!

**Comment by tanberry** [comment]
@janpio and @LumaKernel Do we want to proceed with that final requested commit, or close this one?

**Comment by janpio** [comment]
This also influences our examples which have a similar code snippet: https://github.com/prisma/prisma-examples/blob/65d21a56d1d8dd928066ecbeb83b611e4a542d9f/javascript/script/script.js#L93-L100 If we want to change something here, we should/need also update our examples over there to match and make sense.

**Comment by millsp** [comment]
If you need help, please stick this PR into the Client team inbox (via "Projects").

**Comment by janpio** [comment]
(I could not figure out how to do that even when using the exact project board name @millsp , `⚡️ Client Team` 🤷 )

**Comment by matthewmueller** [comment]
Fixed in prisma-examples: https://github.com/prisma/prisma-examples/pull/3905

**Comment by matthewmueller** [comment]
Resolved conflicts and merged PR in https://github.com/prisma/docs/pull/3510. Thanks @LumaKernel!

**Comment by andrew-walford-prisma** [comment]
@tanberry @keerlu  This issue is still on our board. It looks like it might be finished. Can we archive it?

**Pull request closed without merging**
