### PR TITLE
feat: Linkable search results

### PR DESCRIPTION
**Pull request by nilubava**
#380

### CODE REVIEW

**Comment by janpio** [comment]
Turned into draft as currently does not work, so not reviewable.

(Using search redirects to https://deploy-preview-3398--prisma2-docs.netlify.app/docs/docs/?query=test&page=1 which is a white page for me)

**Comment by nilubava** [comment]
@janpio The link you mentioned above has 2 `/docs` strings. Try this instead: https://deploy-preview-3398--prisma2-docs.netlify.app/docs/?query=test&page=1

**Comment by nilubava** [comment]
@janpio Can you please review the search behaviour again? The results wont be available since we do not index on branch PRs

**Comment by janpio** [comment]
- Searching now changes the URL to something that could be linked to 👍 
- Opening that URL in a new tab also starts the search again 🥳 
- Clsoing the search windows does not change the URL back though
- I also see no search results at all (which I am not sure should be the case - last I tested this I just saw the same results as on the live site but search generally worked)

**Comment by nilubava** [comment]
@janpio Can you test again and let me know if its good to go?

**Comment by janpio** [comment]
Search does not work for me at all on https://docs-git-linkable-search-prisma.vercel.app/ unfortunately.
The header also looks broken.

**Pull request closed without merging**
