### PR TITLE
feat: custom bullet points for unordered lists

### PR DESCRIPTION
**Pull request by nilubava**
#1180 

Usage 
```
- x List  item 1
- x item 2
```

### CODE REVIEW

**Comment by molebox** [comment]
Is there a preview of this so that we can see how it looks and maybe interact with it?

**Comment by janpio** [comment]
PR does not show anything in the example pages.

**Review by molebox — APPROVED** [review]

**Review by janpio — CHANGES_REQUESTED** [review]
This needs to be rebased for useful Percy results, and also fix the merge conflict.

**Comment by tanberry** [comment]
@nilubava is this still something we want to merge?

**Pull request closed without merging**
