### PR TITLE
fix: heading line height

### LINKED ISSUE #5026: Multi line headline with code formattext text has too little line-height
This is how it looks right now:
image

This is how it could look with some line-height:
image

### PR DESCRIPTION
**Pull request by carlagn**
## Describe this PR

The headings inside the layout's content have a diminished line-height, which ends up overlapping text that contains `<inlinecode />` elements.

This PR also includes an update to the lens package that _**should not**_ affect the layout (as we don't use the `<WebsiteHeader />` from lens anymore. It is updated for consistency.

## Changes

Update `line-height` for headings elements inside the `<Content />` styled component to `35px` (this is tentative, so open to add other better fitting values)

## What issue does this fix?

Fixes #5026 

## Any other relevant information

N/a

### CODE REVIEW

**Review by nilubava — APPROVED** [review]

**Comment by janpio** [comment]
The Percy and Lostpixel changes are scary. Do we have some example pages where this should fix something that was broken before?

**Comment by carlagn** [comment]
> The Percy and Lostpixel changes are scary. Do we have some example pages where this should fix something that was broken before?

You're right. I changed it so there wouldn't be so many changes. For now the only heading `line-height` affected is for those that **have** an `<inlinecode />` element. Previously it was an update to all headings' `line-height`.

So before percy had 110 files with visual regressions and now it came down to a more sensible number of 51.

**Comment by meletj** [comment]
> The Percy and Lostpixel changes are scary. Do we have some example pages where this should fix something that was broken before?

This particular title is one with the issue - https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-5#cockroachdb-provider-is-now-required-when-connecting-to-a-cockroachdb-database
I'm going through the LP changes now.

**Comment by meletj** [comment]
The line height added is potentially too high - see in this screenshot. I know it's problematic when we have a title with capitalised words (such as https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-5#cockroachdb-provider-is-now-required-when-connecting-to-a-cockroachdb-database) 
Can we maybe find a middle ground? 

Screenshot 2023-09-12 at 13 29 09

**Comment by carlagn** [comment]
> The line height added is potentially too high - see in this screenshot. I know it's problematic when we have a title with capitalised words (such as https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-5#cockroachdb-provider-is-now-required-when-connecting-to-a-cockroachdb-database) Can we maybe find a middle ground?
> 
> Screenshot 2023-09-12 at 13 29 09

Sure. Any of these look better for you?
| 20px line height | 25px | 30px | 35px (as set by the PR) |
| ----- | ----- | ----- | ----- |
| Screenshot 2023-09-12 at 13 22 53 | Screenshot 2023-09-12 at 13 22 45 | Screenshot 2023-09-12 at 13 22 35 | Screenshot 2023-09-12 at 13 24 46 |

**Comment by meletj** [comment]
> > The line height added is potentially too high - see in this screenshot. I know it's problematic when we have a title with capitalised words (such as https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-5#cockroachdb-provider-is-now-required-when-connecting-to-a-cockroachdb-database) Can we maybe find a middle ground?
> > Screenshot 2023-09-12 at 13 29 09
> 
> Sure. Any of these look better for you?
> 
> 20px line height	25px	30px	35px (as set by the PR)
> Screenshot 2023-09-12 at 13 22 53	Screenshot 2023-09-12 at 13 22 45	Screenshot 2023-09-12 at 13 22 35	Screenshot 2023-09-12 at 13 24 46

i think 30px would work best

**Comment by meletj** [comment]
Still seeing some missing line height - for example this page
https://docs-1xephz165-prisma.vercel.app/concepts/components/prisma-schema/relations/troubleshooting-relations 

Screenshot 2023-09-12 at 17 17 23

**Comment by carlagn** [comment]
> Still seeing some missing line height - for example this page https://docs-1xephz165-prisma.vercel.app/concepts/components/prisma-schema/relations/troubleshooting-relations
> 
> Screenshot 2023-09-12 at 17 17 23

@meletj nope, it's there :/ 

Screenshot 2023-09-12 at 16 30 10

For reference this is the unset version:
Screenshot 2023-09-12 at 16 32 24

I updated the value of line-height to `1.3`, looks like it's a close-enough value to `30px`. They're definitely being set on headings with `<inlinecode />` elements, some just may appear a little different due to the font-size of the heading.

**Comment by janpio** [comment]
I think I see an (almost) unchanged line-height on https://docs-git-fix-title-line-height-prisma.vercel.app/

https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-5#cockroachdb-provider-is-now-required-when-connecting-to-a-cockroachdb-database
image

vs.

https://docs-git-fix-title-line-height-prisma.vercel.app/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-5#cockroachdb-provider-is-now-required-when-connecting-to-a-cockroachdb-database
image

**Comment by janpio** [comment]
Better!

image
=>
image

(Changes that LP highlights are all good as well)

**Review by janpio — APPROVED** [review]

**Review by meletj — APPROVED** [review]

**Pull request merged**
