### PR TITLE
change error reference headings for sidenav 

### PR DESCRIPTION
**Pull request by Jolg42**

### CODE REVIEW

**Comment by molebox** [comment]
Whats this about @Jolg42? Where the sub headings not showing up in the side nav?

**Comment by Jolg42** [comment]
@molebox indeed, with this PR, at least "Error codes" now shows up

Screen Shot 2021-04-16 at 15 27 32

Probably enough?

**Comment by Jolg42** [comment]
Link https://deploy-preview-1572--prisma2-docs.netlify.app/docs/reference/api-reference/error-reference#error-codes

**Comment by mhwelander** [comment]
@Jolg42 Added `tocDepth: 2` to show H3s - merging now 🙌

**Pull request merged**
