### PR TITLE
chore: hide cookie banner for percy diffs

### LINKED ISSUE #3227: Percy + Cookie Banner
The cookie banner should be made invisible for Percy, similar to how we did for some images and other things.

Reason: https://github.com/prisma/docs/pull/3226#issuecomment-1145929931

### PR DESCRIPTION
**Pull request by Jolg42**
Reduce noise, easier to review diff / read text that can sometime hide behind

Closes https://github.com/prisma/docs/issues/3227

### CODE REVIEW

**Comment by tanberry** [comment]
Whoa, this is fantastic, thank you @Jolg42 !! Just saw it, nice.

Can I go ahead and merge this? @Jolg42 , did you have a reason for wanting to wait til 4.1? Or by applying that milestone, are you saying "Let's for sure do this in 4.1"?

**Comment by Jolg42** [comment]
@tanberry No need to wait, not sure why a milestone was added.

If that looks good to you, go for merging it 🙌🏼

**Comment by janpio** [comment]
(The Milestone was to make sure this is not merged before/during the 4.0.0 merge bonanza that happened yesterday)

**Comment by janpio** [comment]
(And the closing was me fat fingering the keyboard instead of just commenting. Sorry)

**Pull request merged**
