### PR TITLE
Fix dotenv example in migration script

### PR DESCRIPTION
**Pull request by eliliam**
## Describe this PR
Fixed documentation example for using dotenv in your NPM scripts.

## Changes

Removed the double hyphen(`--`) as that's no longer the way to do it in `dotenv`.

### CODE REVIEW

**Comment by janpio** [comment]
Did that change in a specific version?

**Comment by eliliam** [comment]
I'm not sure if it's a recent change or not, but I noticed that the example in the docs didn't work. Here's the link to the latest version that shows a working example: https://www.npmjs.com/package/dotenv-cli

**Comment by janpio** [comment]
Hmmm, isn't this exactly our case? https://github.com/entropitor/dotenv-cli#flags-to-the-underlying-command
```
$ dotenv -e .my-env -- mvn exec:java -Dexec.args="-g -f"
```

**Comment by nikolasburk** [comment]
@eliliam did you get a chance to take look at Jan's comment? Any thoughts on how to proceed with this PR?

**Comment by nikolasburk** [comment]
Hey @eliliam, we're cleaning up PRs so I'm taking the liberty to close this one! Feel free to reopen it any time and thanks for taking the time to make Prisma's documentation better 💚

**Pull request closed without merging**
