### PR TITLE
Update 00-deploying-to-heroku.md

### PR DESCRIPTION
**Pull request by abulhuman**
The current push command results in 
```
error: src refspec main does not match any
error: failed to push some refs to 'https://git.heroku.com/your-app-name.git'
```

### CODE REVIEW

**Review by janpio — CHANGES_REQUESTED** [review]
I think newer Heroku deployments only use `main`.

**Comment by abulhuman** [comment]
> I think newer Heroku deployments only use `main`.

I followed the guide to that point and only replacing `main` by `master` in the command worked.

**Comment by abulhuman** [comment]
> I think newer Heroku deployments only use `main`.

more like newer version of git is required where the `master` branch is replaced by `main` by default.

And I think it should made clear from the beginning on the prerequisites section of the guide that the command `git init` should result in a `main` branch rather than a `master` branch.

**Comment by janpio** [comment]
Yes, that might be valid - but that should be an issue then and not a PR that just replaces `main` with `master`. If this would be merged, many people could not work with the instructions any more.

**Comment by abulhuman** [comment]
> Yes, that might be valid - but that should be an issue then and not a PR that just replaces `main` with `master`. If this would be merged, many people could not work with the instructions any more.

Understood sir.

**Comment by 2color** [comment]
I resolved this by ensuring that in the beginning of the guide, you're instructed to change to the `main` branch: https://github.com/prisma/docs/commit/ea282f1bf57f7e91517e26fe72c7f15b0c4b2d63

**Pull request closed without merging**
