### PR TITLE
Update 125-creating-the-prisma-schema.mdx

### PR DESCRIPTION
**Pull request by Nditah**
Fix: Update Post Schema:   Change user to author and userId to authorId

### CODE REVIEW

**Comment by janpio** [comment]
Why this change? Is the current version broken? Is this "just" a question of style?

**Comment by Nditah** [comment]
Sir, the reason for the change is *Logical Consistency.*

The Article in at least 3 places discusses the schema cited *author* and
*authorId*.

https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/mongodb/querying-the-database-typescript-mongodb

Thank you.

**Comment by tanberry** [comment]
Thanks @Nditah for raising this question.... I'm not sure that changing `user` to `author` is the best way to demonstrate the relation between those two. This relation is explained [here](https://www.prisma.io/docs/concepts/components/prisma-schema/relations#relation-fields) in our docs.... 

@matthewmueller can you take a look at this and share your opinion, please?

**Comment by tanberry** [comment]
Let's go ahead and merge this, thanks @Nditah , and I'll open a new Issue for going through that whole set of docs and making them more consistent about `userID` versus `authorID`.

**Pull request merged**
