### PR TITLE
add prisma-generator-fake-data to 'Community generators'

### PR DESCRIPTION
**Pull request by luisrudge**
## Describe this PR

Add new generator to the list

### CODE REVIEW

**Review by janpio — APPROVED** [review]
Nice one!

Does it deal with relations? Prisma used to have a tool called `prisma-test-utils` a few years ago which did similar things, and relations were really hard to get right.

**Comment by luisrudge** [comment]
@janpio thanks! it doesn't handle relations, but it makes it so much easier to create test data!
This was taken from our production app:
```ts
beforeEach(async () => {
  instructor = await db.user.create({
    data: {
      ...fakeUser(),
      institution: {
        create: {
          ...fakeInstitution(),
        },
      },
      role: 'instructor',
    },
  });
  student = await db.user.create({
    data: {
      ...fakeUser(),
      institution: {
        create: {
          ...fakeInstitution(),
        },
      },
      role: 'student',
    },
  });
});
```

**Comment by nikolasburk** [comment]
Hey @luisrudge, thanks a lot for this PR and apologies for the delay! `prisma-generator-fake-data` looks great 🎉

**Comment by luisrudge** [comment]
@nikolasburk Thanks! I appreciate it. I opened a follow-up PR to remove the full link to match the other generators. It was an oversight on my part 😅 
https://github.com/prisma/docs/pull/5471

**Pull request merged**
