### PR TITLE
docs: add relation name for consistency

### PR DESCRIPTION
**Pull request by devpolo**
## Describe this PR

Replacing every `@relation("Name")` by `@relation(name: "Name")` for consistency.

### CODE REVIEW

**Comment by janpio** [comment]
Why do you suggest to make `name` explicit in all relation attributes?

**Comment by devpolo** [comment]
To maintain uniformity, why is the name attribute present in some instances in the documentation and absent in others?

**Comment by janpio** [comment]
That might just be a mistake. The default for `name` is not to render the attribute name I think, so we should possibly unify in the other direction unless there is a good reason to be verbose in this example.

**Comment by sabinadams** [comment]
> That might just be a mistake. The default for `name` is not to render the attribute name I think, so we should possibly unify in the other direction unless there is a good reason to be verbose in this example.

I agree here. Explicitly adding the `name` attribute in a real-world schema could (and likely would) negatively impact the size and readability of the document. The default should be to not have the `name` attribute in the docs to match what a real schema should contain. 

I can make the switch here. Thanks @devpolo for the change suggestion here!

**Pull request merged**
