### PR TITLE
Update 07-prisma-data-platform.mdx

### PR DESCRIPTION
**Pull request by krychaxp**
When i have this changes in `schema.prisma` file , the `npx prisma generate` works

### CODE REVIEW

**Comment by janpio** [comment]
This should not be necessary if you set the env var when running `prisma generate` as documented in line 131 (Documentation is Linux only it seems)

**Review by janpio — CHANGES_REQUESTED** [review]
see comment

**Comment by tanberry** [comment]
HI @krychaxp are you still interested in discussing this PR? If so great, if not we will go ahead and close it in next few days.

I agree with @janpio that best practice would be to define `engineType` as a variable when running the `generate` command (or define it in the .env file), but not define in the schema.

But @janpio what did you mean by "Linux only"?

**Comment by janpio** [comment]
> But @janpio what did you mean by "Linux only"?

The documentation in line 131 shows an example that works on Linux/macOS only, not on Windows (where depending on the terminal you do `set ...` or `$env:...` to set an env var).

**Pull request closed without merging**
