### PR TITLE
docs: `nanoid()` schema function

### LINKED ISSUE #4363: Nanoid default value
This just got merged: https://github.com/prisma/prisma-engines/pull/3556

We should document it in a similar way as we document cuid et.al. To here:

https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#cuid

ping @rintaun

### PR DESCRIPTION
**Pull request by rintaun**
## Describe this PR
Documents the newly added `nanoid()` function

## Changes
* Add `nanoid()` where `cuid()`/`uuid()` are mentioned in relevant contexts

## What issue does this fix?
Fixes prisma/docs#4363

### CODE REVIEW

**Comment by rintaun** [comment]
@pimeys @janpio I think I've added the most important bits. Please let me know if I've missed anything!

**Review by janpio — APPROVED** [review]

**Comment by janpio** [comment]
Note for docs team: Implementation is not finished yet, so not to be merged yet.

**Comment by nikolasburk** [comment]
What's the status of the `nanoid()` implementation? Is it still being worked on or should we close this PR?

**Comment by Jolg42** [comment]
@nikolasburk I made this PR a draft for now. This is blocked by some work that still needs to happen but is currently not planned, see https://github.com/prisma/prisma/issues/17199 for more details.

**Comment by nikolasburk** [comment]
I would actually close this one @Jolg42. When we know that `nanoid()` is coming, we can make a fresh plan for documenting it. (This current PR will be a pain to merge anyways due to the merge conflicts and all the changes that have happened to the content since the PR was opened.)

**Comment by janpio** [comment]
As written in DM as well, I disagree with this. Someone invested a lot of time and effort to find all the places where this should be documented. At least we should turn this into an issue and link this PR here so there is a _chance_ of this being found again for when we need all these locations.

**Comment by Jolg42** [comment]
@janpio I closed it because it's already linked in https://github.com/prisma/prisma/issues/17199.
Feel free to re-open if you want.

**Pull request closed without merging**
