### PR TITLE
docs: quick start update findMany needs argument of empty object

### PR DESCRIPTION
**Pull request by benschac**
```
> dev
> ts-node ./script.ts

{
  then: [Function: then],
  requestTransaction: [Function: requestTransaction],
  catch: [Function: catch],
  finally: [Function: finally],
  posts: [Function (anonymous)]
} allUsers
```
- const allUsers = await prisma.user.findMany();

```
> dev
> ts-node ./script.ts

[
  { id: 1, email: 'sarah@prisma.io', name: 'Sarah' },
  { id: 2, email: 'maria@prisma.io', name: 'Maria' }
] allUsers
➜  starter npm run dev
```
- const allUsers = await prisma.user.findMany({});

using node v.14.16.0

### CODE REVIEW

**Comment by benschac** [comment]
```
 "devDependencies": {
    "prisma": "2.21.0",
    "ts-node": "9.1.1",
    "typescript": "4.2.3"
  },
 ```

**Comment by m-abdelwahab** [comment]
I just cloned the starter repo and `findMany()` didn't require an empty object. 🤔

https://user-images.githubusercontent.com/27310414/114844267-ea0bb800-9dda-11eb-80d8-89b7cd5d4e1e.mp4

**Comment by m-abdelwahab** [comment]
Do you mind cloning the starter repo and try with the same query? Let me know if the issue persists

**Comment by benschac** [comment]
Hi, I borked this. I didn't originally `await` the `findMany`. Thanks for looking and the support.

**Pull request closed without merging**
