### PR TITLE
[FIX] switch zeit now to Vercel Now for prisma docs

### PR DESCRIPTION
**Pull request by Developerayo**
- Zeit just rebranded to Vercel and this PR changes the deployment guidelines to deployment
- Now still remains Now but ZEIT is no longer zeit but Vercel as of today

### CODE REVIEW

**Comment by janpio** [comment]
I think Now is actually also just "Vercel" now: https://www.notion.so/Frequently-Asked-Questions-c726facaf7cc41c095ba49aeea90219e

**Comment by Developerayo** [comment]
Yes! that's quite true, thank's for pointing that out

> Changes reflected

**Comment by janpio** [comment]
Additional note: This should probably only be merged after the actual example is also renamed.

**Comment by Developerayo** [comment]
Quite true!
I'll send a separate PR for that on the Prisma-example repo

**Comment by mhwelander** [comment]
Hi! You were way ahead of us with this - I will close the PR only because the changes were included in #374; thank you 💚 so much for taking the time.

**Pull request closed without merging**
