### PR TITLE
Typo at Introduction

### PR DESCRIPTION
**Pull request by luisejrobles**
Changed
cecause -> **because**

> Note that cecause the Prisma Client node module contains specific context about your Prisma schema, it's sometimes referred to as a "smart node module". 

Note that because the Prisma Client node module contains specific context about your Prisma schema, it's sometimes referred to as a "smart node module". :heavy_check_mark:

### CODE REVIEW

**Comment by luisejrobles** [comment]
Issue #191

**Comment by luisejrobles** [comment]
#191

**Comment by nikolasburk** [comment]
Thanks a lot for catching this @luisejrobles 🎉

**Comment by luisejrobles** [comment]
happy to help :smile:

**Pull request merged**
