### PR TITLE
fix: stop lowercase of urls

### LINKED ISSUE #1518: Case sensitive links in markdown are rendered in lowercase
Some links are case sensitive, for example: 
- This works https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey
- But this doesn't: https://docs.aws.amazon.com/iam/latest/userguide/id_credentials_access-keys.html#using_createaccesskey

Unfortunately, when adding a link with uppercase characters in markdown, the markdown renderer converts the link to lowercase which breaks the link.

The current workaround I found is to use `<a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey">AWS Docs</a> in the markdown.

Example of the workaround in the docs: https://github.com/prisma/docs/blame/fc389a7d392a44268d7ecceba3550aa6a0af75cd/content/300-guides/200-deployment/400-deploying-to-aws-lambda.mdx#L39

Would be good to get this fixed so we don't have to use the workaround.

### PR DESCRIPTION
**Pull request by Jolg42**
## Describe this PR

Found references through https://github.com/prisma/docs/pull/1943

## What issue does this fix?

Fixes https://github.com/prisma/docs/issues/1518

Some external links rely on the casing.

### CODE REVIEW

**Comment by Jolg42** [comment]
Looks like 2 links needs an update 
```
10:09:50 AM: warning 1 broken links found on /docs/guides/database/using-prisma-with-planetscale/
10:09:50 AM: warning  57:365  #how-to-add-in-missing-relations-after-Introspection
10:09:50 AM: ⠀
10:09:50 AM: warning 1 broken links found on /docs/reference/api-reference/prisma-client-reference/
10:09:50 AM: warning 927:54   #deleteMany
10:09:50 AM: ⠀
10:09:50 AM: error "gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:
10:09:50 AM: 2 broken links found
10:09:50 AM: 
10:09:50 AM: 
10:09:50 AM:   Error: 2 broken links found
10:09:50 AM:   
```

**Comment by Jolg42** [comment]
Looks like we need to go to the page mentioned and fix the links, probably just make the anchor lowercase there

**Comment by Jolg42** [comment]
Example, see nova link working now in Markdown style 
https://deploy-preview-2840--prisma2-docs.netlify.app/docs/guides/development-environment/editor-setup#nova

**Review by nilubava — APPROVED** [review]

**Comment by tanberry** [comment]
Thanks @Jolg42 !!

**Pull request merged**
