### PR TITLE
fix: Right-side toc highlight

### LINKED ISSUE #4627: TOC scrolling underline breaks because of not-in-TOC-included headlines
Details: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1680183795248509

### PR DESCRIPTION
**Pull request by carlagn**
Update prisma-client-reference tocDepth

### CODE REVIEW

**Comment by nilubava** [comment]
@carlagn Is this PR ready for review?

**Review by janpio — DISMISSED** [review]
breaks indentation of prisma schema examples

**Comment by janpio** [comment]
why the blanket change from 2 to 3 headline levels?

**Comment by carlagn** [comment]
@janpio 

> why the blanket change from 2 to 3 headline levels?

We just defined these numbers, but the behaviour should be the same. Previously `tocDepth` wasn't impacting code at all (it was always read as `undefined`), hence the issues with scroll highlighting on the right toc. Now we define 2 as default (it goes up to h2 headings), and set the depth for up to what heading we want (if we have h3 headings in the content we want to show on toc, we define front matter with `tocDepth: 3`).

> breaks indentation of prisma schema examples

interestingly enough this indentation break is caused by prettier 🤔 (L#277...L#282)

⚠️ **EDIT:** Updated on [this commit](https://github.com/prisma/docs/pull/4690/commits/594520a952b046cbbf446d15a48086cf0823af5b).

Screenshot 2023-05-10 at 10 52 08

**Review by ruheni — APPROVED** [review]

**Comment by carlagn** [comment]
This PR **does not** solve prettier issues with code blocks using the `prisma` language. 

To separate context, `prisma` code prettier runs are disabled with `<!-- prettier-ignore -->` as needed, and a new PR is created to tackle updates to `prettier-plugin-prisma` here: https://github.com/prisma/docs/pull/4762

**Pull request merged**
